module.exports = [
  {
    category: "Eye Cream",
    skinType: "Sensetive",
    dayNight: "Day & Night",
    brand: "kiehl's",
    description: "Creamy eye treatment with Avocado",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9Mi6h1RJekSfzhiH3G7awpMQNfwBQwkmgkQ&usqp=CAU",
    price: 149,
    qty: 200,
  },
  {
    category: "Toner",
    skinType: "All",
    dayNight: "Day & Night",
    brand: "Fresh",
    description: "Fresh rose deep hydration facial toner",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStpEgvywwgOnASozgbrQ9K0vqp1nWR9FRbBg&usqp=CAU",
    price: 205,
    qty: 100,
  },
  {
    category: "Toner",
    skinType: "Dry",
    dayNight: "Day & Night",
    brand: "Pixi",
    description: "Pixi Glow Tonic",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvtVZ4oZdIObwwbkc82FMTZbtDrQeGHPEzfw&usqp=CAU",
    price: 205,
    qty: 100,
  },
  {
    category: "Serum",
    skinType: "All",
    dayNight: "Night",
    brand: "Estee Lauder",
    description: "Advanced night repaier serum",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRTcRIkVodGSWZYPuH0a-UmwXP-Fxg8eIMWw&usqp=CAU",
    price: 245,
    qty: 300,
  },
  {
    category: "cleanser",
    skinType: "Oily",
    dayNight: "Day & Night",
    brand: "La roche posay cleanser",
    description: "Gently cleansing the skin without drying it",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSObsX7B408p-c5ogLz4_PNrdz8hSwYksDwAvXagBB4bFveiMnSg59WHT0PclYYjXqKZj4&usqp=CAU",
    price: 80,
    qty: 100,
  },
  {
    category: "Moisturizer",
    skinType: "Dry",
    dayNight: "Day & Night",
    brand: "Clinique",
    description: "Deep hyderate your skin leacing it soft and fresh",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrWqRFIU8bE68lYLeAYcXPiDBdOHKZm3LEsw&usqp=CAU",
    price: 114,
    qty: 100,
  },
];
